---
efiBootLoader: "grub"
efiBootloaderId: "AniOS"
installEFIFallback: true
installHybridGRUB: false

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

kernelParams: [ "quiet" ]
