---
displaymanagers:
  - sddm

defaultDesktopEnvironment:
  executable: "/usr/local/bin/anios-session"
  desktopFile: "anios"

basicSetup: false
sysconfigSetup: false
sddm:
  configuration_file: "/etc/sddm.conf"
