---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: true
  - name: "sddm.service"
    action: "enable"
    mandatory: true
  - name: "bluetooth.service"
    action: "enable"
    mandatory: false
  - name: "fstrim.timer"
    action: "enable"
    mandatory: false
  - name: "systemd-timesyncd.service"
    action: "enable"
    mandatory: false
  - name: "power-profiles-daemon.service"
    action: "enable"
    mandatory: true
