# AniOS needs a working connection because the target is installed from Arch repos.
---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
  requiredRam: 2.0
  requiredStorage: 30.0
  internetCheckUrl: "https://archlinux.org/"
  check:
    - ram
    - internet
    - root
    - power
  required:
    - ram
    - internet
    - root

geoip:
  style: "none"
  url: "https://geoip.kde.org/v1/ubiquity"
  selector: "CountryCode"

languageIcon: set-language
