// We're going to use ydotool
// See /usr/include/linux/input-event-codes.h for keycodes

const defaultLayout = "English (US)";

// Every layout is a full-size (100%) keyboard: a main block, the nav cluster
// and the numpad, laid out on the same lattice a keycap is sold on. Each row
// spans 23 keyboard units - 15 for the main block, 3 for the nav cluster, 4
// for the numpad and half a unit of clear air between each - and a row that
// spans anything else is a row whose right-hand clusters sit somewhere the
// rows above and below do not. tst_osk_layouts.qml fails on one.
//
// One spacer object, reused: a gap is half a unit wide (key_shapes.js) and
// the wider ones are runs of it, so padding a row out costs a handful of
// these rather than a shape per width.
const gap = { keytype: "spacer", label: "", shape: "empty" };

const byName = {
    "English (US)": {
        name_short: "US",
        description: "QWERTY - Full",
        comment: "Like physical keyboard",
        // A normal key looks like this: {keytype: "normal", label: "a", labelShift: "A", shape: "normal", keycode: 30}
        // A modkey looks like this: {keytype: "modkey", label: "Ctrl", shape: "control", keycode: 29}
        keys: [
            [
                { keytype: "normal", label: "Esc", shape: "fn", keycode: 1 },
                gap, gap,
                { keytype: "normal", label: "F1", shape: "fn", keycode: 59 },
                { keytype: "normal", label: "F2", shape: "fn", keycode: 60 },
                { keytype: "normal", label: "F3", shape: "fn", keycode: 61 },
                { keytype: "normal", label: "F4", shape: "fn", keycode: 62 },
                gap,
                { keytype: "normal", label: "F5", shape: "fn", keycode: 63 },
                { keytype: "normal", label: "F6", shape: "fn", keycode: 64 },
                { keytype: "normal", label: "F7", shape: "fn", keycode: 65 },
                { keytype: "normal", label: "F8", shape: "fn", keycode: 66 },
                gap,
                { keytype: "normal", label: "F9", shape: "fn", keycode: 67 },
                { keytype: "normal", label: "F10", shape: "fn", keycode: 68 },
                { keytype: "normal", label: "F11", shape: "fn", keycode: 87 },
                { keytype: "normal", label: "F12", shape: "fn", keycode: 88 },
                gap,
                { keytype: "normal", label: "PrtSc", shape: "fn", keycode: 99 },
                { keytype: "normal", label: "ScrLk", shape: "fn", keycode: 70 },
                { keytype: "normal", label: "Pause", shape: "fn", keycode: 119 },
                gap, gap, gap, gap, gap, gap, gap, gap, gap
            ],
            [
                { keytype: "normal", label: "`", labelShift: "~", shape: "normal", keycode: 41 },
                { keytype: "normal", label: "1", labelShift: "!", shape: "normal", keycode: 2 },
                { keytype: "normal", label: "2", labelShift: "@", shape: "normal", keycode: 3 },
                { keytype: "normal", label: "3", labelShift: "#", shape: "normal", keycode: 4 },
                { keytype: "normal", label: "4", labelShift: "$", shape: "normal", keycode: 5 },
                { keytype: "normal", label: "5", labelShift: "%", shape: "normal", keycode: 6 },
                { keytype: "normal", label: "6", labelShift: "^", shape: "normal", keycode: 7 },
                { keytype: "normal", label: "7", labelShift: "&", shape: "normal", keycode: 8 },
                { keytype: "normal", label: "8", labelShift: "*", shape: "normal", keycode: 9 },
                { keytype: "normal", label: "9", labelShift: "(", shape: "normal", keycode: 10 },
                { keytype: "normal", label: "0", labelShift: ")", shape: "normal", keycode: 11 },
                { keytype: "normal", label: "-", labelShift: "_", shape: "normal", keycode: 12 },
                { keytype: "normal", label: "=", labelShift: "+", shape: "normal", keycode: 13 },
                { keytype: "normal", label: "Backspace", shape: "backspace", keycode: 14 },
                gap,
                { keytype: "normal", label: "Ins", shape: "normal", keycode: 110 },
                { keytype: "normal", label: "Home", shape: "normal", keycode: 102 },
                { keytype: "normal", label: "PgUp", shape: "normal", keycode: 104 },
                gap,
                { keytype: "normal", label: "Num", shape: "normal", keycode: 69 },
                { keytype: "normal", label: "/", shape: "normal", keycode: 98 },
                { keytype: "normal", label: "*", shape: "normal", keycode: 55 },
                { keytype: "normal", label: "-", shape: "normal", keycode: 74 }
            ],
            [
                { keytype: "normal", label: "Tab", shape: "tab", keycode: 15 },
                { keytype: "normal", label: "q", labelShift: "Q", shape: "normal", keycode: 16 },
                { keytype: "normal", label: "w", labelShift: "W", shape: "normal", keycode: 17 },
                { keytype: "normal", label: "e", labelShift: "E", shape: "normal", keycode: 18 },
                { keytype: "normal", label: "r", labelShift: "R", shape: "normal", keycode: 19 },
                { keytype: "normal", label: "t", labelShift: "T", shape: "normal", keycode: 20 },
                { keytype: "normal", label: "y", labelShift: "Y", shape: "normal", keycode: 21 },
                { keytype: "normal", label: "u", labelShift: "U", shape: "normal", keycode: 22 },
                { keytype: "normal", label: "i", labelShift: "I", shape: "normal", keycode: 23 },
                { keytype: "normal", label: "o", labelShift: "O", shape: "normal", keycode: 24 },
                { keytype: "normal", label: "p", labelShift: "P", shape: "normal", keycode: 25 },
                { keytype: "normal", label: "[", labelShift: "{", shape: "normal", keycode: 26 },
                { keytype: "normal", label: "]", labelShift: "}", shape: "normal", keycode: 27 },
                { keytype: "normal", label: "\\", labelShift: "|", shape: "backslash", keycode: 43 },
                gap,
                { keytype: "normal", label: "Del", shape: "normal", keycode: 111 },
                { keytype: "normal", label: "End", shape: "normal", keycode: 107 },
                { keytype: "normal", label: "PgDn", shape: "normal", keycode: 109 },
                gap,
                { keytype: "normal", label: "7", shape: "normal", keycode: 71 },
                { keytype: "normal", label: "8", shape: "normal", keycode: 72 },
                { keytype: "normal", label: "9", shape: "normal", keycode: 73 },
                { keytype: "normal", label: "+", shape: "numpadTall", keycode: 78 }
            ],
            [
                { keytype: "normal", label: "Caps", shape: "caps", keycode: 58 },
                { keytype: "normal", label: "a", labelShift: "A", shape: "normal", keycode: 30 },
                { keytype: "normal", label: "s", labelShift: "S", shape: "normal", keycode: 31 },
                { keytype: "normal", label: "d", labelShift: "D", shape: "normal", keycode: 32 },
                { keytype: "normal", label: "f", labelShift: "F", shape: "normal", keycode: 33 },
                { keytype: "normal", label: "g", labelShift: "G", shape: "normal", keycode: 34 },
                { keytype: "normal", label: "h", labelShift: "H", shape: "normal", keycode: 35 },
                { keytype: "normal", label: "j", labelShift: "J", shape: "normal", keycode: 36 },
                { keytype: "normal", label: "k", labelShift: "K", shape: "normal", keycode: 37 },
                { keytype: "normal", label: "l", labelShift: "L", shape: "normal", keycode: 38 },
                { keytype: "normal", label: ";", labelShift: ":", shape: "normal", keycode: 39 },
                { keytype: "normal", label: "'", labelShift: '"', shape: "normal", keycode: 40 },
                { keytype: "normal", label: "Enter", shape: "enter", keycode: 28 },
                gap, gap, gap, gap, gap, gap, gap, gap,
                { keytype: "normal", label: "4", shape: "normal", keycode: 75 },
                { keytype: "normal", label: "5", shape: "normal", keycode: 76 },
                { keytype: "normal", label: "6", shape: "normal", keycode: 77 }
            ],
            [
                { keytype: "modkey", label: "Shift", labelShift: "Shift", labelCaps: "Caps", shape: "shift", keycode: 42 },
                { keytype: "normal", label: "z", labelShift: "Z", shape: "normal", keycode: 44 },
                { keytype: "normal", label: "x", labelShift: "X", shape: "normal", keycode: 45 },
                { keytype: "normal", label: "c", labelShift: "C", shape: "normal", keycode: 46 },
                { keytype: "normal", label: "v", labelShift: "V", shape: "normal", keycode: 47 },
                { keytype: "normal", label: "b", labelShift: "B", shape: "normal", keycode: 48 },
                { keytype: "normal", label: "n", labelShift: "N", shape: "normal", keycode: 49 },
                { keytype: "normal", label: "m", labelShift: "M", shape: "normal", keycode: 50 },
                { keytype: "normal", label: ",", labelShift: "<", shape: "normal", keycode: 51 },
                { keytype: "normal", label: ".", labelShift: ">", shape: "normal", keycode: 52 },
                { keytype: "normal", label: "/", labelShift: "?", shape: "normal", keycode: 53 },
                { keytype: "modkey", label: "Shift", labelShift: "Shift", labelCaps: "Caps", shape: "shiftRight", keycode: 54 },
                gap,
                gap, gap,
                { keytype: "normal", label: "↑", shape: "normal", keycode: 103 },
                gap, gap,
                gap,
                { keytype: "normal", label: "1", shape: "normal", keycode: 79 },
                { keytype: "normal", label: "2", shape: "normal", keycode: 80 },
                { keytype: "normal", label: "3", shape: "normal", keycode: 81 },
                { keytype: "normal", label: "Enter", shape: "numpadTall", keycode: 96 }
            ],
            [
                { keytype: "modkey", label: "Ctrl", shape: "control", keycode: 29 },
                { keytype: "modkey", label: "Super", shape: "mod", keycode: 125 },
                { keytype: "modkey", label: "Alt", shape: "mod", keycode: 56 },
                { keytype: "normal", label: "Space", shape: "space", keycode: 57 },
                { keytype: "modkey", label: "Alt", shape: "mod", keycode: 100 },
                { keytype: "modkey", label: "Super", shape: "mod", keycode: 126 },
                { keytype: "normal", label: "Menu", shape: "mod", keycode: 127 },
                { keytype: "modkey", label: "Ctrl", shape: "control", keycode: 97 },
                gap,
                { keytype: "normal", label: "←", shape: "normal", keycode: 105 },
                { keytype: "normal", label: "↓", shape: "normal", keycode: 108 },
                { keytype: "normal", label: "→", shape: "normal", keycode: 106 },
                gap,
                { keytype: "normal", label: "0", shape: "numpadZero", keycode: 82 },
                { keytype: "normal", label: ".", shape: "normal", keycode: 83 }
            ]
        ]
    },
    "German": {
        name_short: "DE",
        description: "QWERTZ - Full",
        comment: "Keyboard layout commonly used in German-speaking countries",
        keys: [
            [
                { keytype: "normal", label: "Esc", shape: "fn", keycode: 1 },
                gap, gap,
                { keytype: "normal", label: "F1", shape: "fn", keycode: 59 },
                { keytype: "normal", label: "F2", shape: "fn", keycode: 60 },
                { keytype: "normal", label: "F3", shape: "fn", keycode: 61 },
                { keytype: "normal", label: "F4", shape: "fn", keycode: 62 },
                gap,
                { keytype: "normal", label: "F5", shape: "fn", keycode: 63 },
                { keytype: "normal", label: "F6", shape: "fn", keycode: 64 },
                { keytype: "normal", label: "F7", shape: "fn", keycode: 65 },
                { keytype: "normal", label: "F8", shape: "fn", keycode: 66 },
                gap,
                { keytype: "normal", label: "F9", shape: "fn", keycode: 67 },
                { keytype: "normal", label: "F10", shape: "fn", keycode: 68 },
                { keytype: "normal", label: "F11", shape: "fn", keycode: 87 },
                { keytype: "normal", label: "F12", shape: "fn", keycode: 88 },
                gap,
                { keytype: "normal", label: "Druck", shape: "fn", keycode: 99 },
                { keytype: "normal", label: "Rollen", shape: "fn", keycode: 70 },
                { keytype: "normal", label: "Pause", shape: "fn", keycode: 119 },
                gap, gap, gap, gap, gap, gap, gap, gap, gap
            ],
            [
                { keytype: "normal", label: "^", labelShift: "°", labelAlt: "′", shape: "normal", keycode: 41 },
                { keytype: "normal", label: "1", labelShift: "!", labelAlt: "¹", shape: "normal", keycode: 2 },
                { keytype: "normal", label: "2", labelShift: "\"", labelAlt: "²", shape: "normal", keycode: 3 },
                { keytype: "normal", label: "3", labelShift: "§", labelAlt: "³", shape: "normal", keycode: 4 },
                { keytype: "normal", label: "4", labelShift: "$", labelAlt: "¼", shape: "normal", keycode: 5 },
                { keytype: "normal", label: "5", labelShift: "%", labelAlt: "½", shape: "normal", keycode: 6 },
                { keytype: "normal", label: "6", labelShift: "&", labelAlt: "¬", shape: "normal", keycode: 7 },
                { keytype: "normal", label: "7", labelShift: "/", labelAlt: "{", shape: "normal", keycode: 8 },
                { keytype: "normal", label: "8", labelShift: "(", labelAlt: "[", shape: "normal", keycode: 9 },
                { keytype: "normal", label: "9", labelShift: ")", labelAlt: "]", shape: "normal", keycode: 10 },
                { keytype: "normal", label: "0", labelShift: "=", labelAlt: "}", shape: "normal", keycode: 11 },
                { keytype: "normal", label: "ß", labelShift: "?", labelAlt: "\\", shape: "normal", keycode: 12 },
                { keytype: "normal", label: "´", labelShift: "`", labelAlt: "¸", shape: "normal", keycode: 13 },
                { keytype: "normal", label: "⟵", shape: "backspace", keycode: 14 },
                gap,
                { keytype: "normal", label: "Einfg", shape: "normal", keycode: 110 },
                { keytype: "normal", label: "Pos1", shape: "normal", keycode: 102 },
                { keytype: "normal", label: "Bild↑", shape: "normal", keycode: 104 },
                gap,
                { keytype: "normal", label: "Num", shape: "normal", keycode: 69 },
                { keytype: "normal", label: "/", shape: "normal", keycode: 98 },
                { keytype: "normal", label: "*", shape: "normal", keycode: 55 },
                { keytype: "normal", label: "-", shape: "normal", keycode: 74 }
            ],
            [
                { keytype: "normal", label: "Tab ⇆", shape: "tab", keycode: 15 },
                { keytype: "normal", label: "q", labelShift: "Q", labelAlt: "@", shape: "normal", keycode: 16 },
                { keytype: "normal", label: "w", labelShift: "W", labelAlt: "ſ", shape: "normal", keycode: 17 },
                { keytype: "normal", label: "e", labelShift: "E", labelAlt: "€", shape: "normal", keycode: 18 },
                { keytype: "normal", label: "r", labelShift: "R", labelAlt: "¶", shape: "normal", keycode: 19 },
                { keytype: "normal", label: "t", labelShift: "T", labelAlt: "ŧ", shape: "normal", keycode: 20 },
                { keytype: "normal", label: "z", labelShift: "Z", labelAlt: "←", shape: "normal", keycode: 21 },
                { keytype: "normal", label: "u", labelShift: "U", labelAlt: "↓", shape: "normal", keycode: 22 },
                { keytype: "normal", label: "i", labelShift: "I", labelAlt: "→", shape: "normal", keycode: 23 },
                { keytype: "normal", label: "o", labelShift: "O", labelAlt: "ø", shape: "normal", keycode: 24 },
                { keytype: "normal", label: "p", labelShift: "P", labelAlt: "þ", shape: "normal", keycode: 25 },
                { keytype: "normal", label: "ü", labelShift: "Ü", labelAlt: "¨", shape: "normal", keycode: 26 },
                { keytype: "normal", label: "+", labelShift: "*", labelAlt: "~", shape: "normal", keycode: 27 },
                // The ISO Enter is an L, and stays two keys where the numpad's
                // + and Enter became one: 1.5u on this row against 1.25u on
                // the next, offset a quarter unit by the wider Caps below it,
                // so no single rectangle on the lattice is that shape. This is
                // its upper arm; the lower one is the last key of the row
                // below, on the same keycode.
                { keytype: "normal", label: "↵", shape: "enterIsoTop", keycode: 28 },
                gap,
                { keytype: "normal", label: "Entf", shape: "normal", keycode: 111 },
                { keytype: "normal", label: "Ende", shape: "normal", keycode: 107 },
                { keytype: "normal", label: "Bild↓", shape: "normal", keycode: 109 },
                gap,
                { keytype: "normal", label: "7", shape: "normal", keycode: 71 },
                { keytype: "normal", label: "8", shape: "normal", keycode: 72 },
                { keytype: "normal", label: "9", shape: "normal", keycode: 73 },
                { keytype: "normal", label: "+", shape: "numpadTall", keycode: 78 }
            ],
            [
                { keytype: "normal", label: "Feststell", shape: "caps", keycode: 58 },
                { keytype: "normal", label: "a", labelShift: "A", labelAlt: "æ", shape: "normal", keycode: 30 },
                { keytype: "normal", label: "s", labelShift: "S", labelAlt: "ſ", shape: "normal", keycode: 31 },
                { keytype: "normal", label: "d", labelShift: "D", labelAlt: "ð", shape: "normal", keycode: 32 },
                { keytype: "normal", label: "f", labelShift: "F", labelAlt: "đ", shape: "normal", keycode: 33 },
                { keytype: "normal", label: "g", labelShift: "G", labelAlt: "ŋ", shape: "normal", keycode: 34 },
                { keytype: "normal", label: "h", labelShift: "H", labelAlt: "ħ", shape: "normal", keycode: 35 },
                { keytype: "normal", label: "j", labelShift: "J", labelAlt: "", shape: "normal", keycode: 36 },
                { keytype: "normal", label: "k", labelShift: "K", labelAlt: "ĸ", shape: "normal", keycode: 37 },
                { keytype: "normal", label: "l", labelShift: "L", labelAlt: "ł", shape: "normal", keycode: 38 },
                { keytype: "normal", label: "ö", labelShift: "Ö", labelAlt: "˝", shape: "normal", keycode: 39 },
                { keytype: "normal", label: "ä", labelShift: 'Ä', labelAlt: "^", shape: "normal", keycode: 40 },
                { keytype: "normal", label: "#", labelShift: '\'', labelAlt: "’", shape: "normal", keycode: 43 },
                { keytype: "normal", label: "↵", shape: "enterIsoBottom", keycode: 28 },
                gap, gap, gap, gap, gap, gap, gap, gap,
                { keytype: "normal", label: "4", shape: "normal", keycode: 75 },
                { keytype: "normal", label: "5", shape: "normal", keycode: 76 },
                { keytype: "normal", label: "6", shape: "normal", keycode: 77 }
            ],
            [
                { keytype: "modkey", label: "Shift", labelShift: "Shift ⇧", labelCaps: "Locked ⇩", shape: "shiftIso", keycode: 42 },
                { keytype: "normal", label: "<", labelShift: ">", labelAlt: "|", shape: "normal", keycode: 86 },
                { keytype: "normal", label: "y", labelShift: "Y", labelAlt: "»", shape: "normal", keycode: 44 },
                { keytype: "normal", label: "x", labelShift: "X", labelAlt: "«", shape: "normal", keycode: 45 },
                { keytype: "normal", label: "c", labelShift: "C", labelAlt: "¢", shape: "normal", keycode: 46 },
                { keytype: "normal", label: "v", labelShift: "V", labelAlt: "„", shape: "normal", keycode: 47 },
                { keytype: "normal", label: "b", labelShift: "B", labelAlt: "“", shape: "normal", keycode: 48 },
                { keytype: "normal", label: "n", labelShift: "N", labelAlt: "”", shape: "normal", keycode: 49 },
                { keytype: "normal", label: "m", labelShift: "M", labelAlt: "µ", shape: "normal", keycode: 50 },
                { keytype: "normal", label: ",", labelShift: ";", labelAlt: "·", shape: "normal", keycode: 51 },
                { keytype: "normal", label: ".", labelShift: ":", labelAlt: "…", shape: "normal", keycode: 52 },
                { keytype: "normal", label: "-", labelShift: "_", labelAlt: "–", shape: "normal", keycode: 53 },
                { keytype: "modkey", label: "Shift", labelShift: "Shift ⇧", labelCaps: "Locked ⇩", shape: "shiftRight", keycode: 54 },
                gap,
                gap, gap,
                { keytype: "normal", label: "↑", shape: "normal", keycode: 103 },
                gap, gap,
                gap,
                { keytype: "normal", label: "1", shape: "normal", keycode: 79 },
                { keytype: "normal", label: "2", shape: "normal", keycode: 80 },
                { keytype: "normal", label: "3", shape: "normal", keycode: 81 },
                { keytype: "normal", label: "↵", shape: "numpadTall", keycode: 96 }
            ],
            [
                { keytype: "modkey", label: "Strg", shape: "control", keycode: 29 },
                { keytype: "modkey", label: "Super", shape: "mod", keycode: 125 },
                { keytype: "modkey", label: "Alt", shape: "mod", keycode: 56 },
                { keytype: "normal", label: "Leertaste", shape: "space", keycode: 57 },
                { keytype: "modkey", label: "Alt Gr", shape: "mod", keycode: 100 },
                { keytype: "modkey", label: "Super", shape: "mod", keycode: 126 },
                { keytype: "normal", label: "Menü", shape: "mod", keycode: 127 },
                { keytype: "modkey", label: "Strg", shape: "control", keycode: 97 },
                gap,
                { keytype: "normal", label: "←", shape: "normal", keycode: 105 },
                { keytype: "normal", label: "↓", shape: "normal", keycode: 108 },
                { keytype: "normal", label: "→", shape: "normal", keycode: 106 },
                gap,
                { keytype: "normal", label: "0", shape: "numpadZero", keycode: 82 },
                { keytype: "normal", label: ",", shape: "normal", keycode: 83 }
            ]
        ]
    },
    "Russian": {
        name_short: "RU",
        description: "ЙЦУКЕН - Full",
        comment: "Standard Russian keyboard layout",
        keys: [
            [
                { keytype: "normal", label: "Esc", shape: "fn", keycode: 1 },
                gap, gap,
                { keytype: "normal", label: "F1", shape: "fn", keycode: 59 },
                { keytype: "normal", label: "F2", shape: "fn", keycode: 60 },
                { keytype: "normal", label: "F3", shape: "fn", keycode: 61 },
                { keytype: "normal", label: "F4", shape: "fn", keycode: 62 },
                gap,
                { keytype: "normal", label: "F5", shape: "fn", keycode: 63 },
                { keytype: "normal", label: "F6", shape: "fn", keycode: 64 },
                { keytype: "normal", label: "F7", shape: "fn", keycode: 65 },
                { keytype: "normal", label: "F8", shape: "fn", keycode: 66 },
                gap,
                { keytype: "normal", label: "F9", shape: "fn", keycode: 67 },
                { keytype: "normal", label: "F10", shape: "fn", keycode: 68 },
                { keytype: "normal", label: "F11", shape: "fn", keycode: 87 },
                { keytype: "normal", label: "F12", shape: "fn", keycode: 88 },
                gap,
                { keytype: "normal", label: "PrtSc", shape: "fn", keycode: 99 },
                { keytype: "normal", label: "ScrLk", shape: "fn", keycode: 70 },
                { keytype: "normal", label: "Pause", shape: "fn", keycode: 119 },
                gap, gap, gap, gap, gap, gap, gap, gap, gap
            ],
            [
                { keytype: "normal", label: "ё", labelShift: "Ё", shape: "normal", keycode: 41 },
                { keytype: "normal", label: "1", labelShift: "!", shape: "normal", keycode: 2 },
                { keytype: "normal", label: "2", labelShift: "\"", shape: "normal", keycode: 3 },
                { keytype: "normal", label: "3", labelShift: "№", shape: "normal", keycode: 4 },
                { keytype: "normal", label: "4", labelShift: ";", shape: "normal", keycode: 5 },
                { keytype: "normal", label: "5", labelShift: "%", shape: "normal", keycode: 6 },
                { keytype: "normal", label: "6", labelShift: ":", shape: "normal", keycode: 7 },
                { keytype: "normal", label: "7", labelShift: "?", shape: "normal", keycode: 8 },
                { keytype: "normal", label: "8", labelShift: "*", shape: "normal", keycode: 9 },
                { keytype: "normal", label: "9", labelShift: "(", shape: "normal", keycode: 10 },
                { keytype: "normal", label: "0", labelShift: ")", shape: "normal", keycode: 11 },
                { keytype: "normal", label: "-", labelShift: "_", shape: "normal", keycode: 12 },
                { keytype: "normal", label: "=", labelShift: "+", shape: "normal", keycode: 13 },
                { keytype: "normal", label: "Backspace", shape: "backspace", keycode: 14 },
                gap,
                { keytype: "normal", label: "Ins", shape: "normal", keycode: 110 },
                { keytype: "normal", label: "Home", shape: "normal", keycode: 102 },
                { keytype: "normal", label: "PgUp", shape: "normal", keycode: 104 },
                gap,
                { keytype: "normal", label: "Num", shape: "normal", keycode: 69 },
                { keytype: "normal", label: "/", shape: "normal", keycode: 98 },
                { keytype: "normal", label: "*", shape: "normal", keycode: 55 },
                { keytype: "normal", label: "-", shape: "normal", keycode: 74 }
            ],
            [
                { keytype: "normal", label: "Tab", shape: "tab", keycode: 15 },
                { keytype: "normal", label: "й", labelShift: "Й", shape: "normal", keycode: 16 },
                { keytype: "normal", label: "ц", labelShift: "Ц", shape: "normal", keycode: 17 },
                { keytype: "normal", label: "у", labelShift: "У", shape: "normal", keycode: 18 },
                { keytype: "normal", label: "к", labelShift: "К", shape: "normal", keycode: 19 },
                { keytype: "normal", label: "е", labelShift: "Е", shape: "normal", keycode: 20 },
                { keytype: "normal", label: "н", labelShift: "Н", shape: "normal", keycode: 21 },
                { keytype: "normal", label: "г", labelShift: "Г", shape: "normal", keycode: 22 },
                { keytype: "normal", label: "ш", labelShift: "Ш", shape: "normal", keycode: 23 },
                { keytype: "normal", label: "щ", labelShift: "Щ", shape: "normal", keycode: 24 },
                { keytype: "normal", label: "з", labelShift: "З", shape: "normal", keycode: 25 },
                { keytype: "normal", label: "х", labelShift: "Х", shape: "normal", keycode: 26 },
                { keytype: "normal", label: "ъ", labelShift: "Ъ", shape: "normal", keycode: 27 },
                { keytype: "normal", label: "\\", labelShift: "/", shape: "backslash", keycode: 43 },
                gap,
                { keytype: "normal", label: "Del", shape: "normal", keycode: 111 },
                { keytype: "normal", label: "End", shape: "normal", keycode: 107 },
                { keytype: "normal", label: "PgDn", shape: "normal", keycode: 109 },
                gap,
                { keytype: "normal", label: "7", shape: "normal", keycode: 71 },
                { keytype: "normal", label: "8", shape: "normal", keycode: 72 },
                { keytype: "normal", label: "9", shape: "normal", keycode: 73 },
                { keytype: "normal", label: "+", shape: "numpadTall", keycode: 78 }
            ],
            [
                { keytype: "normal", label: "Caps", shape: "caps", keycode: 58 },
                { keytype: "normal", label: "ф", labelShift: "Ф", shape: "normal", keycode: 30 },
                { keytype: "normal", label: "ы", labelShift: "Ы", shape: "normal", keycode: 31 },
                { keytype: "normal", label: "в", labelShift: "В", shape: "normal", keycode: 32 },
                { keytype: "normal", label: "а", labelShift: "А", shape: "normal", keycode: 33 },
                { keytype: "normal", label: "п", labelShift: "П", shape: "normal", keycode: 34 },
                { keytype: "normal", label: "р", labelShift: "Р", shape: "normal", keycode: 35 },
                { keytype: "normal", label: "о", labelShift: "О", shape: "normal", keycode: 36 },
                { keytype: "normal", label: "л", labelShift: "Л", shape: "normal", keycode: 37 },
                { keytype: "normal", label: "д", labelShift: "Д", shape: "normal", keycode: 38 },
                { keytype: "normal", label: "ж", labelShift: "Ж", shape: "normal", keycode: 39 },
                { keytype: "normal", label: "э", labelShift: "Э", shape: "normal", keycode: 40 },
                { keytype: "normal", label: "Enter", shape: "enter", keycode: 28 },
                gap, gap, gap, gap, gap, gap, gap, gap,
                { keytype: "normal", label: "4", shape: "normal", keycode: 75 },
                { keytype: "normal", label: "5", shape: "normal", keycode: 76 },
                { keytype: "normal", label: "6", shape: "normal", keycode: 77 }
            ],
            [
                { keytype: "modkey", label: "Shift", labelShift: "Shift", labelCaps: "Caps", shape: "shift", keycode: 42 },
                { keytype: "normal", label: "я", labelShift: "Я", shape: "normal", keycode: 44 },
                { keytype: "normal", label: "ч", labelShift: "Ч", shape: "normal", keycode: 45 },
                { keytype: "normal", label: "с", labelShift: "С", shape: "normal", keycode: 46 },
                { keytype: "normal", label: "м", labelShift: "М", shape: "normal", keycode: 47 },
                { keytype: "normal", label: "и", labelShift: "И", shape: "normal", keycode: 48 },
                { keytype: "normal", label: "т", labelShift: "Т", shape: "normal", keycode: 49 },
                { keytype: "normal", label: "ь", labelShift: "Ь", shape: "normal", keycode: 50 },
                { keytype: "normal", label: "б", labelShift: "Б", shape: "normal", keycode: 51 },
                { keytype: "normal", label: "ю", labelShift: "Ю", shape: "normal", keycode: 52 },
                { keytype: "normal", label: ".", labelShift: ",", shape: "normal", keycode: 53 },
                { keytype: "modkey", label: "Shift", labelShift: "Shift", labelCaps: "Caps", shape: "shiftRight", keycode: 54 },
                gap,
                gap, gap,
                { keytype: "normal", label: "↑", shape: "normal", keycode: 103 },
                gap, gap,
                gap,
                { keytype: "normal", label: "1", shape: "normal", keycode: 79 },
                { keytype: "normal", label: "2", shape: "normal", keycode: 80 },
                { keytype: "normal", label: "3", shape: "normal", keycode: 81 },
                { keytype: "normal", label: "Enter", shape: "numpadTall", keycode: 96 }
            ],
            [
                { keytype: "modkey", label: "Ctrl", shape: "control", keycode: 29 },
                { keytype: "modkey", label: "Super", shape: "mod", keycode: 125 },
                { keytype: "modkey", label: "Alt", shape: "mod", keycode: 56 },
                { keytype: "normal", label: "Space", shape: "space", keycode: 57 },
                { keytype: "modkey", label: "Alt", shape: "mod", keycode: 100 },
                { keytype: "modkey", label: "Super", shape: "mod", keycode: 126 },
                { keytype: "normal", label: "Menu", shape: "mod", keycode: 127 },
                { keytype: "modkey", label: "Ctrl", shape: "control", keycode: 97 },
                gap,
                { keytype: "normal", label: "←", shape: "normal", keycode: 105 },
                { keytype: "normal", label: "↓", shape: "normal", keycode: 108 },
                { keytype: "normal", label: "→", shape: "normal", keycode: 106 },
                gap,
                { keytype: "normal", label: "0", shape: "numpadZero", keycode: 82 },
                { keytype: "normal", label: ".", shape: "normal", keycode: 83 }
            ]
        ]
    }
}
