[Autologin]
User=anios
Session=anios
Relogin=false

[Theme]
# Theme Qylock Wuthering Waves (đã bổ sung khung nền tĩnh và tải video trễ).
Current=wuwa

[General]
Numlock=on

[Users]
MinimumUid=500
MaximumUid=60513
RememberLastUser=true
RememberLastSession=true
